In [7]:
import numpy as np
import pandas as pd
price = np.array([100,200,300])
print(price*2)

[200 400 600]

In [6]:
price  = [100,200,300]
for index,i in enumerate(price):
    i = i * 2
    price[index]=i
print(price)

[200, 400, 600]

In [8]:
df = pd.DataFrame({"Sales":[250,800,1200,450]})

In [9]:
df

   Sales
0    250
1    800
2   1200
3    450

In [13]:
print(df['Sales'].values)

[ 250  800 1200  450]

In [14]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]

In [18]:
s = np.linspace(0,10,5)
s

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
s = np.arange(0,10,2)
s

array([0, 2, 4, 6, 8])

In [25]:
e = np.zeros(5 ,dtype=int)
print(e)
print(type(e[0]))

[0 0 0 0 0]
<class 'numpy.int64'>

In [28]:
f = np.ones(4, dtype=int)
f

array([1, 1, 1, 1])

In [52]:
g = np.array([[1,2,3],
              [4,5,6]])
g[0,0:2]

array([1, 2])

In [34]:
g.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
g = g.reshape(3,2)

In [42]:
g.ndim

2

In [41]:
g.shape

(3, 2)

In [46]:
g[1][1]

np.int64(4)

In [47]:
g.size

6

In [53]:
g.dtype

dtype('int64')

In [55]:
w = np.array([[1,2,3],[4,5,6]])
w[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
a = np.array([10,4,7,12,15])
a

array([10,  4,  7, 12, 15])

In [61]:
a[(a>5) & (a<12)]

array([10,  7])

In [66]:
q = np.array([5,12,7,28,3])
t = np.where(q>10, "High", "Low")

print(q,t)

[ 5 12  7 28  3] ['Low' 'High' 'Low' 'High' 'Low']

In [70]:
a = np.array([10,20,30,40])
print(a[a>10].sum(), a.sum(), a.mean(), a.min(), a.max())

90 100 25.0 10 40

In [71]:
a = np.array([[1,2,3],[4,5,6]])
print(a.sum() , a.sum(axis=0), a.sum(axis=1))

21 [5 7 9] [ 6 15]

In [72]:
df['Tier'] = np.where(df["Sales"]>1000 , "high", "low")
df

   Sales  Tier
0    250   low
1    800   low
2   1200  high
3    450   low