In [5]:
import sys
!"{sys.executable}" -m pip install sqlalchemy pyodbc

Requirement already satisfied: sqlalchemy in c:\Users\Malik Nisar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.53)
Requirement already satisfied: pyodbc in c:\Users\Malik Nisar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.3.0)
Requirement already satisfied: greenlet>=1 in c:\Users\Malik Nisar\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Malik Nisar\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import requests 
import pandas as pd

API_KEY = "b238da37213d7fa7c9edc37eec6312a5"
City = "Lahore"
url = 'https://api.openweathermap.org/data/2.5/weather'
params = {"q": City, "appid": API_KEY, "units": "metric"}
res = requests.get(url, params=params)

In [9]:
resp = res.json()
df = pd.DataFrame([resp])
df

,coord,weather,base,main,visibility,wind,clouds,dt,sys,timezone,id,name,cod
0,"{'lon': 74.3436, 'lat': 31.5497}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 30.99, 'feels_like': 37.57, 'temp_min...",10000,"{'speed': 1.03, 'deg': 330}",{'all': 2},1789480553,"{'type': 1, 'id': 7585, 'country': 'PK', 'sunr...",18000,1172451,Lahore,200

In [10]:
print("Response Status Code:", res.status_code)

Response Status Code: 200

In [11]:
df["name"]

0    Lahore
Name: name, dtype: str

In [19]:
df.iloc[0, 0:5].to_frame()

                                                            0
coord                        {'lon': 74.3436, 'lat': 31.5497}
weather     [{'id': 800, 'main': 'Clear', 'description': '...
base                                                 stations
main        {'temp': 30.99, 'feels_like': 37.57, 'temp_min...
visibility                                              10000

In [20]:
df.iloc[0, 0:5].to_frame().T

,coord,weather,base,main,visibility
0,"{'lon': 74.3436, 'lat': 31.5497}","[{'id': 800, 'main': 'Clear', 'description': '...",stations,"{'temp': 30.99, 'feels_like': 37.57, 'temp_min...",10000

In [26]:
df.iloc[[0], 2:12]

,base,main,visibility,wind,clouds,dt,sys,timezone,id,name
0,stations,"{'temp': 30.99, 'feels_like': 37.57, 'temp_min...",10000,"{'speed': 1.03, 'deg': 330}",{'all': 2},1789480553,"{'type': 1, 'id': 7585, 'country': 'PK', 'sunr...",18000,1172451,Lahore

In [36]:
cities = ["Lahore", "Karachi", "Islamabad"]
df_list = []

for city in cities:
    url = 'https://api.openweathermap.org/data/2.5/weather'
    params = {"q": city, "appid": API_KEY, "units": "metric"}
    res = requests.get(url, params=params)
    resp = res.json()
    df = pd.DataFrame([resp])
    df['temp'] = df['main'].str.get("temp")
    df['clarity'] = df["weather"].str[0].str.get("description")
    df['humidity'] = df["main"].str.get("humidity")
    df_list.append(df[["name", "temp", "clarity","humidity", "wind", "sys"]])


df_cities = pd.concat(df_list, ignore_index=True)
df_cities

,name,temp,clarity,humidity,wind,sys
0,Lahore,29.99,clear sky,70,"{'speed': 1.54, 'deg': 330}","{'type': 1, 'id': 7585, 'country': 'PK', 'sunr..."
1,Karachi,29.90,overcast clouds,74,"{'speed': 3.09, 'deg': 220}","{'type': 1, 'id': 7576, 'country': 'PK', 'sunr..."
2,Islamabad,27.76,broken clouds,57,"{'speed': 3.59, 'deg': 40, 'gust': 4.16}","{'country': 'PK', 'sunrise': 1789433434, 'suns..."

In [39]:
rows = []
for city in cities:
    url = 'https://api.openweathermap.org/data/2.5/weather'
    params = {"q": city, "appid": API_KEY, "units": "metric"}
    res = requests.get(url, params=params)
    resp = res.json()
    rows.append({
        "city": resp['name'],
        'temp': resp['main']['temp'],
        'humidity': resp['main']['humidity'],
        'clarity': resp['weather'][0]['description'],
    })

weather_df = pd.DataFrame(rows)
weather_df

        city   temp  humidity          clarity
0     Lahore  29.99        70        clear sky
1    Karachi  29.90        74  overcast clouds
2  Islamabad  27.76        57    broken clouds